configs =  {
    'martian': {
        'health': 1000,
        'shield': 1000,
        'energy': 1000,
        'recharge': 50,
        'fire_rate': 100,  # lower is faster
        'max_velocity': 10,
        'max_energy': 1000,
        'turn_speed': 5,
        'image_ship': 'assets/ships/martian.png',
        'image_engines': 'assets/ships/martian-engines.png',
        'special': "teleport",
        'special_energy': 100,
        'fire_sound': 'assets/sounds/shot_5.wav',
        'special_sound': 'assets/sounds/change_1.wav',
        'hit_other_sound': 'assets/sounds/hit1.wav',
        'explosion_sound': 'assets/sounds/explosion - muffled big.wav',
        'fire_sound_volume': 0.9,
        'special_sound_volume': 0.4,
        'hit_other_sound_volume': 0.5,
        'explosion_sound_volume': 1.0,

        'projectile': {
            'type': "green shot",
            'health': 100,
            'shield': 50,
            'energy': 50,
            'recharge': 50,
            'fire_rate': 0,
            'explode': False,
            'damage': 100,
            'velocity': 50,
            'max_velocity': 50,
            'expiry_time': 60,
            }
        },

    'plutonian': {
                    'health': 2000,
                    'shield': 0,
                    'energy': 500,
                    'recharge': 10,
                    'fire_rate': 500,
                    'p_health': 100,
                    'p_shield': 50,
                    'p_energy': 50 ,
                    'p_recharge': 50,
                    'p_fire_rate': 0,
                    'p_explode': False,
                    'p_damage': 100,
                    'p_velocity': 50,
                    'p_max_velocity': 50        ,
                    'p_expiry_time': 60,
                    'max_velocity': 15,
                    'max_energy': 1000,
                    'turn_speed': 5,
                    'image_ship': 'assets/ships/plutonian_2.png',
                    'image_engines': 'assets/ships/plutonian_2-engines.png',
                    'special': "shield",
                    'special_energy': 100,
                    'fire_sound': 'assets/sounds/fire_2.wav',
                    'special_sound': 'assets/sounds/shot_5.wav',
                    'hit_other_sound': 'assets/sounds/hit2.wav',
                    'explosion_sound': 'assets/sounds/explosion - muffled big.wav',
                    'fire_sound_volume': 0.9,
                    'special_sound_volume': 0.4,
                    'hit_other_sound_volume': 0.5,
                    'explosion_sound_volume': 1.0,
                    
                    'projectile': {
                        'type': "green shot",
                        'health': 100,
                        'shield': 50,
                        'energy': 50,
                        'recharge': 50,
                        'fire_rate': 0,
                        'explode': False,
                        'damage': 100,
                        'velocity': 50,
                        'max_velocity': 50,
                        'expiry_time': 60,
                        }

    },
    'zapper': {
                    'health': 500,
                    'shield': 1500,
                    'energy': 250,
                    'recharge': 50,
                    'fire_rate': 500,
                    'p_health': 100,
                    'p_shield': 50,
                    'p_energy': 50 ,
                    'p_recharge': 50,
                    'p_fire_rate': 0,
                    'p_explode': False,
                    'p_damage': 100,
                    'p_velocity': 50,
                    'p_max_velocity': 50,
                    'p_expiry_time': 60,
                    'max_velocity': 15,
                    'max_energy': 500,
                    'turn_speed': 5,
                    'image_ship': 'assets/ships/zapper.png',
                    'image_engines': 'assets/ships/zapper-engines.png',
                    'special': "shield",
                    'special_energy': 100,
                    'fire_sound': 'assets/sounds/beam_3.wav',
                    'special_sound': 'assets/sounds/continuous_1.wav',
                    'hit_other_sound': 'assets/sounds/hit2.wav',
                    'explosion_sound': 'assets/sounds/explosion - muffled big.wav',
                    'fire_sound_volume': 0.9,
                    'special_sound_volume': 0.4,
                    'hit_other_sound_volume': 0.5,
                    'explosion_sound_volume': 1.0,
                    
                    'projectile': {
                        'type': "green shot",
                        'health': 100,
                        'shield': 50,
                        'energy': 50,
                        'recharge': 50,
                        'fire_rate': 0,
                        'explode': False,
                        'damage': 100,
                        'velocity': 50,
                        'max_velocity': 50,
                        'expiry_time': 60,
                        }
    },
    'rocket': {
                    'health': 1000,
                    'shield': 1500,
                    'energy': 250,
                    'recharge': 50,
                    'fire_rate': 1000,
                    'max_velocity': 15,
                    'max_energy': 500,
                    'turn_speed': 5,
                    'image_ship': 'assets/ships/rocket.png',
                    'image_engines': 'assets/ships/rocket-engines.png',
                    'special': "shield",
                    'special_energy': 100,
                    'fire_sound': 'assets/sounds/missile1.wav',
                    'special_sound': 'assets/sounds/continuous_1.wav',
                    'hit_other_sound': 'assets/sounds/hit2.wav',
                    'explosion_sound': 'assets/sounds/explosion - muffled big.wav',
                    'fire_sound_volume': 0.9,
                    'special_sound_volume': 0.5,
                    'hit_other_sound_volume': 0.5,
                    'explosion_sound_volume': 1.0,
                    'projectile': {
                        'type': "missile",
                        'health': 100,
                        'shield': 50,
                        'energy': 50,
                        'recharge': 250,
                        'fire_rate': 0,
                        'explode': False,
                        'damage': 500,
                        'velocity': 0,
                        'max_velocity': 15,
                        'expiry_time': 60,
                        }
    },
    'behemoth': {
                    'health': 500,
                    'shield': 1500,
                    'energy': 250,
                    'recharge': 50,
                    'fire_rate': 500,
                    'p_health': 100,
                    'p_shield': 50,
                    'p_energy': 500,
                    'p_recharge': 50,
                    'p_fire_rate': 0,
                    'p_explode': False,
                    'p_damage': 100,
                    'p_velocity': 50,
                    'p_max_velocity': 50,
                    'p_expiry_time': 60,
                    'max_velocity': 15,
                    'max_energy': 500,
                    'turn_speed': 5,
                    'image_ship': 'assets/ships/behemoth.png',
                    'image_engines': 'assets/ships/behemoth-engines.png',
                    'special': "shield",
                    'special_energy': 100,
                    'fire_sound': 'assets/sounds/beam_3.wav',
                    'special_sound': 'assets/sounds/continuous_1.wav',
                    'hit_other_sound': 'assets/sounds/hit2.wav',
                    'explosion_sound': 'assets/sounds/explosion - muffled big.wav',
                    'fire_sound_volume': 0.9,
                    'special_sound_volume': 0.5,
                    'hit_other_sound_volume': 0.5,
                    'explosion_sound_volume': 1.0,
                    'projectile': {
                        'type': "missile",
                        'health': 100,
                        'shield': 50,
                        'energy': 50,
                        'recharge': 250,
                        'fire_rate': 0,
                        'explode': False,
                        'damage': 500,
                        'velocity': 0,
                        'max_velocity': 15,
                        'expiry_time': 60,
                        }
    },
    'miner': {
                    'health': 500,
                    'shield': 1500,
                    'energy': 250,
                    'recharge': 50,
                    'fire_rate': 500,
                    'p_health': 100,
                    'p_shield': 50,
                    'p_energy': 50 ,
                    'p_recharge': 50,
                    'p_fire_rate': 0,
                    'p_explode': False,
                    'p_damage': 100,
                    'p_velocity': 50,
                    'p_max_velocity': 50        ,
                    'p_expiry_time': 60,
                    'max_velocity': 15,
                    'max_energy': 500,
                    'turn_speed': 5,
                    'image_ship': 'assets/ships/miner.png',
                    'image_engines': 'assets/ships/miner-engines.png',
                    'special': "shield",
                    'special_energy': 100,
                    'fire_sound': 'assets/sounds/beam_3.wav',
                    'special_sound': 'assets/sounds/continuous_1.wav',
                    'hit_other_sound': 'assets/sounds/hit2.wav',
                    'explosion_sound': 'assets/sounds/explosion - muffled big.wav',
                    'fire_sound_volume': 0.9,
                    'special_sound_volume': 0.5,
                    'hit_other_sound_volume': 0.5,
                    'explosion_sound_volume': 1.0,
                    'projectile': {
                        'type': "missile",
                        'health': 100,
                        'shield': 50,
                        'energy': 50,
                        'recharge': 250,
                        'fire_rate': 0,
                        'explode': False,
                        'damage': 500,
                        'velocity': 0,
                        'max_velocity': 15,
                        'expiry_time': 60,
                        }

    }
}